### ISSUE TITLE
Module pfsense_dhcp_static - ARP Static Entry

### ISSUE THREAD

**Issue by csphoenix1** [pfsensible/core#109]
Hello,

First, thanks for this great ansible module :)

I would to know if it's possible to implement the "ARP Table Static Entry" boolean option in the pfsense_dhcp_static module.
It's just a checkbox in the pfsense IHM to "Create an ARP Table Static Entry for this MAC & IP Address pair".

Thank you.

Regards,

**Comment by opoplawski** [comment]
@cmarodrigues Would you be able to take a look at this?

**Comment by cmarodrigues** [comment]
@opoplawski i created the PR #111 to add "ARP Table Static Entry" option but i'm not able to testing because i don't have the environment to test it.

**Comment by opoplawski** [comment]
@csphoenix1 If you are able to test current master to see if it does what you need, that would be greatly appreciated.

**Comment by csphoenix1** [comment]
Hello :)
Yes i'm able to test it.
I'll try a des hours.
I will come back to you soon.
Thanks.

**Comment by csphoenix1** [comment]
Hello,
It work perfectly!
Thank you for your work :)
