### ISSUE TITLE
Unable to run /bin/sh command on pfsense 2.4.5

### ISSUE THREAD

**Issue by kinther** [pfsensible/core#12]
I'm trying to use the pfsensible.core.alias module and running into an issue seen below.  I've set my remote_tmp directory to /tmp as noted in the error message but it appears that the main issue is "Bad -c option"?

`<172.16.0.10> ESTABLISH PARAMIKO SSH CONNECTION FOR USER: admin on PORT 22 TO 172.16.0.10
<172.16.0.10> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /tmp/ansible-tmp-1587412302.8008745-40411721665864 `" && echo ansible-tmp-1587412302.8008745-40411721665864="` echo /tmp/ansible-tmp-1587412302.8008745-40411721665864 `" ) && sleep 0'
fatal: [pfsense]: UNREACHABLE! => {
    "changed": false,
    "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo /tmp/ansible-tmp-1587412302.8008745-40411721665864 `\" && echo ansible-tmp-1587412302.8008745-40411721665864=\"` echo /tmp/ansible-tmp-1587412302.8008745-40411721665864 `\" ), exited with result 2, stderr output: Bad -c option\n",
    "unreachable": true
}`

Please let me know if I can provide any more information on this error.

**Comment by kinther** [comment]
This was due to the admin user logging in to a menu rather than a direct shell - the noted command simply could not run unless it opened a shell first.  Creating a group that put a user directly into shell and logging in as that user "automationuser" fixed the issue.

**Comment by GBenakidis** [comment]
Hi, I want to run a script using node, from shell, and it outputs the error: "/bin/sh: node: not found". Is there any way I can download node in pfsense?

**Comment by opoplawski** [comment]
@GBenakidis Please open a separate discussion for your question with more details about what it is you are trying to do, and why you think pfsensible is the appropriate tool to do it.
