### ISSUE TITLE
Using 'any' interface in a floating rule

### ISSUE THREAD

**Issue by robertkarsai** [pfsensible/core#120]
Hello,
According to the code I could use pfsense_rule on 'any' interface to apply something to all interface when floating: true, but it seems to give an error FAILED! => {"changed": false, "msg": "any is not a valid interface"}. Am I doing something wrong?
Thanks,
Robert

**Comment by opoplawski** [comment]
Can you post your full task and version of pfsensible?

**Comment by opoplawski** [comment]
Also output with verbose `-vvv`

**Comment by robertkarsai** [comment]
Hi, sorry, I just can't seem to be able to reproduce the problem, it was on a Debian 11 system, with ansible 2.10 + pfsensible core 0.5.something, now on Debian 12 + ansible 2.14 + pfsensible 0.6.1 it just works.
BR
Robert

**Comment by opoplawski** [comment]
I can't either, so closing
