### ISSUE TITLE
nat_outbound - wrong dest address

### ISSUE THREAD

**Issue by Avers90** [pfsensible/core#124]
Hello

When I try to add NAT Outbound rule with Ansible with this code:
```python
- name: "PfSense nat outbound | Add NAT outbound traffic rule form 10.3.22.175/32 to 10.1.255.70/32"
  pfsense_nat_outbound:
    descr: "Rule 1"
    interface: "WAN06_VL307_BN"
    source: 10.3.22.175/32
    destination: 10.1.255.70/32
    nonat: true
    state: present
``` 

I get this picture:
<img width="1134" alt="Снимок экрана 2024-04-08 в 09 48 06" src="https://github.com/pfsensible/core/assets/31271932/a11cc2b3-1d2c-4a1f-9898-8079df7c8517">

U can see the dest IP adds with mask in a field - Destination network for the outbound NAT mapping.

Core version is [0.6.1](https://github.com/pfsensible/core/releases/tag/0.6.1)

**Comment by opoplawski** [comment]
I can't reproduce this.  What version of pfSense are you using?

**Comment by opoplawski** [comment]
I suspect you are using pfSense 2.6.0 or earlier, in which case I think you'll need to stick with pfsensible.core < 6.0, or better yet update to pfSense 2.7.2.  pfSense 2.6.0 is unsupported at this point.

**Comment by Avers90** [comment]
Yeap, I'm using pfSense 2.6.0. 

Thanks for the tip. I will try.
