### ISSUE TITLE
pfsensible.core.ca Base64 Encoding Issue

### ISSUE THREAD

**Issue by gambl3** [pfsensible/core#15]
I encountered an issue working with the pfsensible.core.ca module. It appears when using Ansible with Python3 the validate_cert bas64.b64encode(cert) does not work properly. Please see the error message below. My workaround was to manually base64 encode the PEM file and use the encoded value in my playbook but I think the function could be modified to handle this.

**Code in plugin**
def validate_cert(self, cert):
        # TODO - Make sure certificate purpose includes CA
        lines = cert.splitlines()
        if lines[0] == '-----BEGIN CERTIFICATE-----' and lines[-1] == '-----END CERTIFICATE-----':
            return **base64.b64encode(cert)**

Problem encountered on OS CentOS 7.8.2003 Ansible Version: 2.9.9

**Sample: Ansible Playbook used**
- name: Add IPA Certificate Authority
  pfsensible.core.ca:
    name: IPA CA
    certificate: |
      -----BEGIN CERTIFICATE-----
      ..clipped for brevity
      MIIDgjCCAmqgAwIBAgIBATANBgkqhkiG9w0BAQsFADAzMREwDwYDVQQKDAhURVNU
      -----END CERTIFICATE-----
      state: present

**Ansible Error:**
\"/tmp/ansible_pfsensible.core.ca_payload_m7vvdkd5/ansible_pfsensible.core.ca_payload.zip/ansible_collections/pfsensible/core/plugins/modules/ca.py\", line 111, in validate_cert\r\n  File \"/usr/local/lib/python3.7/base64.py\", line 58, in b64encode\r\n    encoded = binascii.b2a_base64(s, newline=False)\r\nTypeError: a bytes-like object is required, not 'str'\r\n", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 

**Tested For fix:**
#!/usr/bin/python3
import base64
data = open(unencoded_pem, "r").read()
#Commented for test
#data=(data.encode('utf-8'))
encoded = base64.b64encode(data)
print(encoded)
Traceback (most recent call last):
  File "./py3fix.py", line 8, in <module>
    encoded = base64.b64encode(data)
  File "/usr/lib64/python3.6/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'

#!/usr/bin/python3
import base64

data = open(unencoded_pem, "r").read()
**data=(data.encode('utf-8'))**
encoded = base64.b64encode(data)
print(encoded)

Output:
b'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURnakNDQW1xZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREF6TVJFd0R3WURWUVFLREFoVVJWTlUKTGt4QlRqRWVNQndHQTFVRUF3d1ZRMlZ5ZEdsbDBwZ0hMSyt5cHUxK3g=='

**Comment by HEG-IT** [comment]
Encountering the same issue on CentOS 8. Workaround seemed to handle the encoding but kept getting "Could not recognize certificate format:". Likely related to my ignorance concerning creating the PEM format from the pfsense export capabilities.

**Comment by opoplawski** [comment]
This is fixed in the upstream opoplawski/pfsense repository, hopefully I can get a new release of pfsensbile out soon.

**Comment by opoplawski** [comment]
FYI - new release is out.
