### ISSUE TITLE
Aggregate module is not working anymore in pfSense-21.02

### ISSUE THREAD

**Issue by MuhammadShaban** [pfsensible/core#19]
Hi, I have just installed the new pfSense version 21.02
and the pfsense_aggregate module is not working anymore. This is the trace:
`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
fatal: [pfin_2]: FAILED! => {"changed": false, "module_stderr": "Shared connection to ########### closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ec2-user/.ansible/tmp/ansible-tmp-1614002528.0419357-46891-200519525228219/AnsiballZ_pfsense_aggregate.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ec2-user/.ansible/tmp/ansible-tmp-1614002528.0419357-46891-200519525228219/AnsiballZ_pfsense_aggregate.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ec2-user/.ansible/tmp/ansible-tmp-1614002528.0419357-46891-200519525228219/AnsiballZ_pfsense_aggregate.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.pfsensible.core.plugins.modules.pfsense_aggregate', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/local/lib/python3.7/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/local/lib/python3.7/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/local/lib/python3.7/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_pfsensible.core.pfsense_aggregate_payload_3oc4rroq/ansible_pfsensible.core.pfsense_aggregate_payload.zip/ansible_collections/pfsensible/core/plugins/modules/pfsense_aggregate.py\", line 1096, in <module>\r\n  File \"/tmp/ansible_pfsensible.core.pfsense_aggregate_payload_3oc4rroq/ansible_pfsensible.core.pfsense_aggregate_payload.zip/ansible_collections/pfsensible/core/plugins/modules/pfsense_aggregate.py\", line 1081, in main\r\n  File \"/tmp/ansible_pfsensible.core.pfsense_aggregate_payload_3oc4rroq/ansible_pfsensible.core.pfsense_aggregate_payload.zip/ansible_collections/pfsensible/core/plugins/modules/pfsense_aggregate.py\", line 618, in __init__\r\n  File \"/tmp/ansible_pfsensible.core.pfsense_aggregate_payload_3oc4rroq/ansible_pfsensible.core.pfsense_aggregate_payload.zip/ansible_collections/pfsensible/core/plugins/module_utils/vlan.py\", line 44, in __init__\r\n  File \"/tmp/ansible_pfsensible.core.pfsense_aggregate_payload_3oc4rroq/ansible_pfsensible.core.pfsense_aggregate_payload.zip/ansible_collections/pfsensible/core/plugins/module_utils/pfsense.py\", line 557, in php\r\n  File \"/usr/local/lib/python3.7/json/__init__.py\", line 348, in loads\r\n    return _default_decoder.decode(s)\r\n  File \"/usr/local/lib/python3.7/json/decoder.py\", line 337, in decode\r\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\r\n  File \"/usr/local/lib/python3.7/json/decoder.py\", line 355, in raw_decode\r\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\r\njson.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}`

Message from gui
`PHP ERROR: Type: 1, File: Standard input code, Line: 2, Message: Uncaught Error: Call to undefined function is_jumbo_capable() in Standard input code:2`

**Comment by f-bor** [comment]
It's the same error as #18.
