### ISSUE TITLE
pfsense_user: bcrypt hash detection logic wants improvement

### ISSUE THREAD

**Issue by tigattack** [pfsensible/core#37]
The logic here: https://github.com/pfsensible/core/blob/92a6186330160a3af631d3e25a103afcdaa972a1/plugins/modules/pfsense_user.py#L156

Could do with some improvement as there are valid bcrypt hashes which start with characters other than `$2b`. For example, I pulled the `config.xml` from one of my pfSense instances (running latest version) and the password hashes begin with `$2y`.

**Comment by opoplawski** [comment]
Thanks.  It does look like there are `$2a` and `$2y` variants.
