### ISSUE TITLE
file not found /cf/conf/config.xml

### ISSUE THREAD

**Issue by samuellsk** [pfsensible/core#38]
trying it with pfsense 2.6.0 (dont know if its compatible)

logging as root

[pfsense]
10.90.0.99 ansible_user=root ansible_ssh_pass=pfsense

running simple thing like creating vlans

---
- name: pfsense_vlans
  hosts: all
  tasks:
  - name: create AMR vlan
    pfsensible.core.pfsense_vlan:
      interface: LAN
      vlan_id: 2
      descr: AMR

package sudo is installed on pfsense
tried with "become" and without
I get file not found /cf/conf/config.xml  , if i login to ssh and go there file its there and my user or root can write it. From webui using edit file and pointing it to /cf/conf/config.xml also works

![image](https://user-images.githubusercontent.com/22764003/184534393-512e12c2-ac32-4138-921d-63631ee44a21.png)

**Comment by stefanfluit-robin** [comment]
I have the same issue.

`TASK [ansible-role-router-configuration : Install sudo] **************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [ansible-role-router-configuration : Add S&S group] *************************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: FileNotFoundError: [Errno 2] No such file or directory: '/cf/conf/config.xml'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/fluit/.ansible/tmp/ansible-tmp-1661955006.8388512-2329418-249489363269926/AnsiballZ_pfsense_group.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/fluit/.ansible/tmp/ansible-tmp-1661955006.8388512-2329418-249489363269926/AnsiballZ_pfsense_group.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/fluit/.ansible/tmp/ansible-tmp-1661955006.8388512-2329418-249489363269926/AnsiballZ_pfsense_group.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.pfsensible.core.plugins.modules.pfsense_group', init_globals=dict(_module_fqn='ansible_collections.pfsensible.core.plugins.modules.pfsense_group', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_pfsensible.core.pfsense_group_payload_c7_s479l/ansible_pfsensible.core.pfsense_group_payload.zip/ansible_collections/pfsensible/core/plugins/modules/pfsense_group.py\", line 226, in <module>\n  File \"/tmp/ansible_pfsensible.core.pfsense_group_payload_c7_s479l/ansible_pfsensible.core.pfsense_group_payload.zip/ansible_collections/pfsensible/core/plugins/modules/pfsense_group.py\", line 220, in main\n  File \"/tmp/ansible_pfsensible.core.pfsense_group_payload_c7_s479l/ansible_pfsensible.core.pfsense_group_payload.zip/ansible_collections/pfsensible/core/plugins/modules/pfsense_group.py\", line 99, in __init__\n  File \"/tmp/ansible_pfsensible.core.pfsense_group_payload_c7_s479l/ansible_pfsensible.core.pfsense_group_payload.zip/ansible_collections/pfsensible/core/plugins/module_utils/module_base.py\", line 25, in __init__\n  File \"/tmp/ansible_pfsensible.core.pfsense_group_payload_c7_s479l/ansible_pfsensible.core.pfsense_group_payload.zip/ansible_collections/pfsensible/core/plugins/module_utils/pfsense.py\", line 56, in __init__\n  File \"/usr/lib64/python3.10/xml/etree/ElementTree.py\", line 1222, in parse\n    tree.parse(source, parser)\n  File \"/usr/lib64/python3.10/xml/etree/ElementTree.py\", line 569, in parse\n    source = open(source, \"rb\")\nFileNotFoundError: [Errno 2] No such file or directory: '/cf/conf/config.xml'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}`

**Comment by opoplawski** [comment]
@samuellsk What is `control`?  My guess it that it is not a pfSense box and as such does not have `/cf/conf/config.xml`.

@stefanfluit-robin Looks like you are trying to run against `localhost` rather than your pfSense box.
