### ISSUE TITLE
interface not detected

### ISSUE THREAD

**Issue by dantealkahfi** [pfsensible/core#39]
Hello,

thank you for this module. 

I'm encountering a problem when i'm tring to use the pfsense_gateway to create a gateway. it throw me this error from my awx

`{
  "msg": "Interface vtnet0 not found",
  "invocation": {
    "module_args": {
      "name": "wangateway",
      "interface": "vtnet0",
      "gateway": "redacted",
      "state": "present",
      "ipprotocol": "inet",
      "descr": "",
      "disabled": false,
      "monitor_disable": false,
      "action_disable": false,
      "force_down": false,
      "weight": 1,
      "nonlocalgateway": false,
      "monitor": null
    }
  },
  "_ansible_no_log": false,
  "changed": false
}`

my playbook is using variable for gateway in pfsense 2.6.0
```

    - name: get interface name
      shell: ifconfig -lu | awk '{print$1}'
      register: interface_get

    - name: debug {{ interface_get.stdout }}
      debug:
        var: interface_get.stdout

    # configure gateway first for interface
    - name: config pfsense gateway
      pfsense_gateway:
        name: 'wangateway'
        # interface: "{{ pfsense_interface_gateway | quote }}"
        interface: "{{interface_get.stdout | quote}}"
        gateway: "{{ pfsense_gateway_address }}"
        state: present
```

**Comment by Sushi1324** [comment]
I have been seeing the same issue with pfsense 2.6.0. It appears that the self.pfsense.interfaces object is not getting the 'descr' value properly filled (in my tests they all equal None), so regardless of what is provided for "interface", it fails.

**Comment by opoplawski** [comment]
I think the issue is that the interface names were restricted to the names in the config file and not device names.  Can you test out #41 and see if that resolves the issue for you?

**Comment by opoplawski** [comment]
You also should be able to use `interface: wan` with the current code.
