### ISSUE TITLE
Wrong type for responderonly in pfsensible.core.pfsense_ipsec

### ISSUE THREAD

**Issue by tgt-ops** [pfsensible/core#53]
I'm trying to create a phase 1 on an IPSec tunnel in Responder Only mode, so i've set `responderonly` to `True`
But It gave me this error : 
`TypeError: cannot serialize True (type bool)`

Documentation states that's a boolean parameter, but I think on the pfsense it's not :

![image](https://user-images.githubusercontent.com/91257500/217283181-340dec90-acc2-4a7e-8153-f1f69da9c9b4.png)

Default value is `False` ant it must be working because it falls back to `Default` on the pfsense.
Can you update the type of this parameter to choices in pfsense_ipsec module ?

**Comment by opoplawski** [comment]
Looks like that parameter was dropped in favor of startaction.  There is also a closeaction paramter as well.  Could you give the startaction branch a try?
