### ISSUE TITLE
Creating the first pfsense_dhcp_static entry for a given interface fails with "IndexError: list index out of range"

### ISSUE THREAD

**Issue by toastboy70** [pfsensible/core#58]
It seems that using this ansible definition:

- name: Add DHCP static mappings
  pfsensible.core.pfsense_dhcp_static:
    name: "{{ item.name }}"
    macaddr: "{{ item.mac }}"
    ipaddr: "{{ item.address }}"
    netif: "{{ item.interface }}"
  loop: "{{ host_mappings }}"

will fail with an error like this if and only if the list of static mappings for the given interface is empty:

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IndexError: list index out of range
failed: [192.168.1.201] (item={'name': 'sony-tv-sitting-room', 'mac': '70:26:05:7b:f7:0e', 'address': '172.16.24.204', 'interface': 'opt2'}) => {"ansible_loop_var": "item", "changed": false, "item": {"address": "172.16.24.204", "interface": "opt2", "mac": "70:26:05:7b:f7:0e", "name": "sony-tv-sitting-room"}, "module_stderr": "Shared connection to 192.168.1.201 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1678623425.479361-92221-106907561307919/AnsiballZ_pfsense_dhcp_static.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1678623425.479361-92221-106907561307919/AnsiballZ_pfsense_dhcp_static.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1678623425.479361-92221-106907561307919/AnsiballZ_pfsense_dhcp_static.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.pfsensible.core.plugins.modules.pfsense_dhcp_static', init_globals=dict(_module_fqn='ansible_collections.pfsensible.core.plugins.modules.pfsense_dhcp_static', _modlib_path=modlib_path),\r\n  File \"/usr/local/lib/python3.8/runpy.py\", line 207, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/local/lib/python3.8/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/local/lib/python3.8/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_pfsensible.core.pfsense_dhcp_static_payload_siiogh9i/ansible_pfsensible.core.pfsense_dhcp_static_payload.zip/ansible_collections/pfsensible/core/plugins/modules/pfsense_dhcp_static.py\", line 362, in <module>\r\n  File \"/tmp/ansible_pfsensible.core.pfsense_dhcp_static_payload_siiogh9i/ansible_pfsensible.core.pfsense_dhcp_static_payload.zip/ansible_collections/pfsensible/core/plugins/modules/pfsense_dhcp_static.py\", line 357, in main\r\n  File \"/tmp/ansible_pfsensible.core.pfsense_dhcp_static_payload_siiogh9i/ansible_pfsensible.core.pfsense_dhcp_static_payload.zip/ansible_collections/pfsensible/core/plugins/module_utils/module_base.py\", line 232, in run\r\n  File \"/tmp/ansible_pfsensible.core.pfsense_dhcp_static_payload_siiogh9i/ansible_pfsensible.core.pfsense_dhcp_static_payload.zip/ansible_collections/pfsensible/core/plugins/module_utils/module_base.py\", line 169, in _add\r\n  File \"/tmp/ansible_pfsensible.core.pfsense_dhcp_static_payload_siiogh9i/ansible_pfsensible.core.pfsense_dhcp_static_payload.zip/ansible_collections/pfsensible/core/plugins/modules/pfsense_dhcp_static.py\", line 296, in _copy_and_add_target\r\n  File \"/tmp/ansible_pfsensible.core.pfsense_dhcp_static_payload_siiogh9i/ansible_pfsensible.core.pfsense_dhcp_static_payload.zip/ansible_collections/pfsensible/core/plugins/modules/pfsense_dhcp_static.py\", line 284, in _find_last_dhcp_static_index\r\nIndexError: list index out of range\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

Manually creating a dummy mapping for each interface before running the ansible means this error is no longer seen.

**Comment by opoplawski** [comment]
This is fixed with #52 - I'll try to get a release out shortly.

**Comment by opoplawski** [comment]
0.5.2 has been pushed to ansible galaxy now.
