### ISSUE TITLE
certtype variable in cert config is not working

### ISSUE THREAD

**Issue by georgetarlas** [pfsensible/core#60]
Seems that variable certtype is missing from cert plugin and has no effect the use of "server". It always creates a user certificate.

**Comment by opoplawski** [comment]
I can't reproduce this issue.  Please give much more information: pfsense version, pfsensible version, sample tasks, play output with -v, openssl x509 -text output of the certificate, etc.

**Comment by georgetarlas** [comment]
The problem was resolved. It seems the root cause was that the certificate we were producing via openssl wasn't the correct type. After we fixed this, the certificate type was accepted / recognized as server certificate.

Just for the history, we have pfsense 2.6 and pfsensible.core 0.5.2.
