### ISSUE TITLE
openvpn_override "A valid IPv4 network must be specified for the tunnel_network"

### ISSUE THREAD

**Issue by SkyHyve** [pfsensible/core#77]
Hi,

I am using pfsensible.core.pfsense_openvpn_override and I am trying to add a client specific override. One of the fields in the GUI is the "Tunnel Network" and you can specify the ip/netmask in cidr notation, allowing for static tunnel ips for specific clients. In the gui you can specify an ip address that is not the network address, e.g. 192.168.0.2/24 as opposed to 192.168.0.0/24, however when testing the pfsensible functionality, it appears to error with fatal: FAILED! => {"changed": false, "msg": "A valid IPv4 network must be specified for tunnel_network."} 
It does not appear to fail when eh network address is specified, but this doesn't allow for the static tunnel addresses

**Comment by opoplawski** [comment]
So the main issue is that we just shouldn't do strict IP network validation on the tunnel_network parameters.  But I also added some basic support for network aliases as well.
