### ISSUE TITLE
TLS key can't be generated for OpenVPN client/server

### ISSUE THREAD

**Issue by TTPBruce** [pfsensible/core#81]
The documentation specifies that you can set tls='generate' to generate a TLS key, however this seems to be un-implemented, as the parameter is required to match the correct format and I can't seem to find anything that would parse the keyword "generate".

https://github.com/pfsensible/core/blob/278676d4c7dc8ee4f1d19feb0135b6f1918bc9d9/plugins/modules/pfsense_openvpn_server.py#L67

https://github.com/pfsensible/core/blob/278676d4c7dc8ee4f1d19feb0135b6f1918bc9d9/plugins/modules/pfsense_openvpn_client.py#L69

**Comment by genofire** [comment]
same problem, i am writing a patch now.

**Comment by opoplawski** [comment]
Another question is how is this to be used in practice?  Presumably you need to collect the key, so I think we need to make the modules return the key when `generate` is used.  Sound good?  Other ideas?

**Comment by TTPBruce** [comment]
Yes, this is how I envisioned using it. Our current processes involve manual copying of the keys, so having the module return the generated key would be useful.

**Comment by opoplawski** [comment]
Okay, PR #107 should return any generated keys.
