### ISSUE TITLE
Wiki documentation for pfsensible.core.group

### ISSUE THREAD

**Issue by darksoul42** [pfsensible/core#9]
https://github.com/pfsensible/core/wiki/pfsensible.core.group

Just a few quirks in documentation.

Documentation states `description` as a parameter, but trying to use it results in the following message:
```Unsupported parameters for (pfsensible.core.group) module: description Supported parameters include: descr, gid, name, priv, scope, state```

Also, `state: present` is not mentioned in the example but actually explicitly required.

**Comment by f-bor** [comment]
Thanks. I have added the `state: present` in the example.

For the description, you misread: it's `descr`, not `description`.

**Comment by darksoul42** [comment]
Actually, the inconsistency was in the examples.

**Comment by f-bor** [comment]
I see. Thanks again for reporting this.
