### ISSUE TITLE
pfsensible.core.pfsense_nat_outbound invert option bug.

### ISSUE THREAD

**Issue by Jonathan-Forbes** [pfsensible/core#92]
I am currently using pfsense+ version 23.05.1-RELEASE (amd64) and pfsensible version 0.5.3. I have created a playbook to create the outbound NAT rules for my firewall but have found that the invert option for the pfsensible.core.pfsense_nat_outbound module does not work as expected. When setting the invert option to true (invert: true) the playbook successfully completes. Although once I check the outbound NAT rules under the pfsense gui I find that the destination is not inverted. After some further digging into the XML it was discovered that there is an issue with how the invert option is implemented. 

Below is what the NAT section of the XML looks like when the configuration is done using pfsensible".

![pfsensible invert true](https://github.com/pfsensible/core/assets/148104330/54105fa7-9a1c-45d3-bb56-e0984d0aa051) 

What is weird is that when the configuration is done manually through the gui it does not create that <invert>yes</invert> tag but instead looks like the following. 

![manual configuration invert true](https://github.com/pfsensible/core/assets/148104330/4fa3b123-732b-4e45-b737-fb03199e356d)

What's even weirder is that once you run the playbook again with the invert option set to true it turns off the manually configured setting all together, the XML looks like the following.

![manual configuration overwritten](https://github.com/pfsensible/core/assets/148104330/49ef3ed0-349d-4ba3-b2de-d5aa4c7d59ee)

After further digging the nonat option was examined at it behaves differently. When it is configured using pfsensible the XML shows the following. 

![pfsensible nonat true](https://github.com/pfsensible/core/assets/148104330/c20b6342-f40d-46f7-8c09-775c3cf95b94)

And when it is configured manually the XML shows what can be seen below.

![manual configuartion nonat true](https://github.com/pfsensible/core/assets/148104330/aee6e921-cb4d-401e-be78-c0bf99155c91)

What's important to note with nonat is that whether it is configured with pfsensible or performed manually it still shows up as working in the pfsense gui.

Any help would be appreciated as currently the only work around is to manually tick the box which obviously is not ideal.

Thanks,
Jonathan Forbes

**Comment by opoplawski** [comment]
Thanks for the report.  Unfortunately nat_outbound is pretty crufty at this point.  The PR should be a quick fix for the issue at hand though.

**Comment by Jonathan-Forbes** [comment]
Just wanted to follow up.

The problem seems to be fixed now.

Cheers

Jonathan

**Comment by opoplawski** [comment]
Thanks for the confirmation.
